### ISSUE TITLE
Single line Newick

### ISSUE THREAD

**Issue by thierryjanssens** [nylander/translate_fasta_headers#1]
Dear Johan,

thank you for developing this useful tool.
I got a bit confused however when I wanted to replace the sequence labels on the final Ne.wick tree.

Error: Tried to look for tree in Newick format (tree description on single line) but didn't find it.

$head substitutions.tree

#NEXUS
begin taxa;
        dimensions ntax=59;
        taxlabels
                'Seq_11'[&FULL="0 - Seq_11 [Y5Y, Y11*, Q12*, A16*, I17*, N18*, E19*, V20*, I21*, N22*, R23*, A24*, I25*, T26*, I27*, I28*, K29*, T30*, K31*, A32*, T33*, T37T, V38V, E41E, S43*, G44*, A46A, G49G, L50*, E51*, T52*, G53*, L58L, S65*, K66*, T68S, E74E, T81T, S89S, E90E, F96F, L97L, S98S, A101A, N112N, H113H, T114T, S115S, A117E, T120I, K122*, K123*, E124*, F128Y, T131T, N133N, L140L, R141R, L146L,

etc ...

Does the entire tree need to be on a single line, then?

Kind regards,

Thierry

**Comment by thierryjanssens** [comment]
I realize it is a Nexus tree, however...

**Comment by nylander** [comment]
No support for Nexus-format. Try to convert to newick.
